version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: repsy-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: repsydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
